package name.ruiz.juanfco.cgi;

public enum Arg {
	HELP, REPLACE, HOLAMUNDO, MAPA2LISTA, 
	EXTRACTDIGITS, EXTRACTDOUBLEFROMSTRING,	EXTRACTLONGFROMSTRING, COMPARACIONES, 
	PROCESADUMMIES, TROCEOCADENA, ELIMINAPARENTESIS,VALIDAFORMATO,
    ARRAYTOSTRING, OBJETOS, FECHAS, REFLEXION
}
